### ISSUE TITLE
Migration fails: allready run the activate-tls.sh script 

### ISSUE THREAD

**Issue by geelenbert** [szaimen/NcVM-migration#4]
I'm getting an error with the latest 22.2.2 VM and the migration script.

When created a new NcVM and running the restore script generated on the old VM, i'm getting this error:
![Screenshot 2021-11-26 at 08 40 13](https://user-images.githubusercontent.com/91923/143544966-fc8c9c9c-df8f-478e-abc2-96d35d498e4a.png)

I've tried it multiple times, but i definitely did not run any TLS or Lets encrypt.

I installed a new VM, installed nothing but the smb addon and run the script.

Any clue what it could be ?

**Comment by szaimen** [comment]
Hi there, thanks for your report! The issue was fixed with https://github.com/szaimen/NcVM-migration/commit/f9b19f30914169a82be3072220960c9436b75e43 but you need to do the same change on your generated restore.sh file or redo the whole process form the beginning (including spinning up the old VM again and running the migration script again.) 
See here whats needs to be removed/changed in your restore script:
![image](https://user-images.githubusercontent.com/42591237/143944619-94f4c05f-a3ac-4259-ae38-ad3f99a70826.png)
